// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace AstralGameplayTags
{
	ASTRALPLAGUE_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	// Declare all of the custom native tags that Lyra will use
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_AutoRun);

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_RequestReset);

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AutoRunning);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);

	// These are mappings from MovementMode enums to GameplayTags associated with those enums (below)
	ASTRALPLAGUE_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	ASTRALPLAGUE_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	ASTRALPLAGUE_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);
};
